name: PR Tests

on: pull_request

permissions:
  contents: read

jobs:
  tests:
    name: Run Tests
    runs-on: macos-15
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v5
    - name: Build and run tests
      run: ./Scripts/build.sh tests
      env:
        DEVELOPER_DIR: '/Applications/Xcode_16.2.app/Contents/Developer'
